# Generated by Django 3.2.13 on 2025-03-19 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_resume'),
        ('jobs', '0003_assessment_assessmentresponse_option_question_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_url', models.URLField()),
                ('status', models.CharField(default='applied', max_length=50)),
                ('application_method', models.CharField(default='manual', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_applications', to='users.studentprofile')),
            ],
        ),
    ]
