# jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('jobs/', views.job_list, name='job_list'),
    path('jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    path('jobs/create/', views.job_create, name='job_create'),
    path('jobs/<int:job_id>/edit/', views.job_edit, name='job_edit'),
    path('jobs/<int:job_id>/delete/', views.job_delete, name='job_delete'),
    path('jobs/scrape/', views.job_scrape, name='job_scrape'),
    path('jobs/scrape/save/', views.save_scraped_job, name='save_scraped_job'),
    path('jobs/<int:job_id>/assign-departments/', views.assign_departments, name='assign_departments'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/create/', views.department_create, name='department_create'),
    path('departments/<int:dept_id>/edit/', views.department_edit, name='department_edit'),
    path('departments/<int:dept_id>/delete/', views.department_delete, name='department_delete'),
    path('departments/<int:dept_id>/jobs/', views.department_jobs, name='department_jobs'),
    path('student/jobs/', views.student_job_list, name='student_job_list'),
    path('student/jobs/<int:job_id>/', views.student_job_detail, name='student_job_detail'),
    path('student/jobs/<int:job_id>/apply/', views.apply_for_job, name='apply_for_job'),
    path('student/applications/', views.my_applications, name='my_applications'),
    path('student/resume/upload/', views.resume_upload, name='resume_upload'),
    path('student/assessment/', views.take_assessment, name='take_assessment'),
    path('student/assessment/<int:assessment_id>/questions/', views.assessment_questions, name='assessment_questions'),
    path('student/assessment/<int:assessment_id>/results/', views.assessment_results, name='assessment_results'),
    path('student/jobs/auto-apply/', views.auto_apply_to_job, name='auto_apply_to_job'),
    path('student/jobs/<int:job_id>/auto-apply/', views.auto_apply_to_job, name='auto_apply_to_job_by_id'),
    path('email-templates/', views.email_template_list, name='email_template_list'),
    path('email-templates/create/', views.email_template_create, name='email_template_create'),
    path('email-templates/<int:template_id>/edit/', views.email_template_edit, name='email_template_edit'),
    path('email-templates/<int:template_id>/delete/', views.email_template_delete, name='email_template_delete'),
    path('send-email/', views.send_email, name='send_email'),
    path('send-email/<int:job_id>/', views.send_email, name='send_email_for_job'),
    path('email-log/', views.email_log, name='email_log'),
    path('api/template/<int:template_id>/', views.get_template_content, name='get_template_content'),
    path('applications/', views.application_list, name='application_list'),
    path('applications/<int:application_id>/', views.view_application, name='view_application'),
    path('applications/<int:application_id>/update-status/', views.update_application_status, name='update_application_status'),
]